spring.application.name=taskmanager

server.port=8088

#POSTGRES DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=maksudloepg

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update